### ISSUE TITLE
Some remaining tasks

### ISSUE THREAD

**Issue by lervag** [lervag/vim-rainbow-lists#1]
- [x] Support for numbered lists
- [x] Support for checkbox lists
- [x] Support for quotes
- [x] Add toggle feature
- [x] Add documentation

See example file here: https://github.com/lervag/vim-rainbow-lists/blob/main/test/example.md

**Comment by nathanbraun** [comment]
It'd also be great to be able to have it automatically load on certain filetypes.

**Comment by lervag** [comment]
Actually, I think it might be easier to simply load automatically through custom config. As an example, if you want to load this plugin for your `.wiki` files, you can add this to your vimrc file:

```vim
augroup vimrc
  autocmd!
  autocmd FileType wiki call rblist#enable()
augroup END
```

**Comment by lervag** [comment]
We're getting close. To complete, it would be nice with a complex example of various types of lists. Could you provide one or more such examples?

**Comment by nathanbraun** [comment]
Sure!

**Comment by nathanbraun** [comment]
> We're getting close. To complete, it would be nice with a complex example of various types of lists. Could you provide one or more such examples?

To be clear, you mean like a screenshot with the various bullet and indentation options (maybe the raw text is also in the documentation too) right?

**Comment by lervag** [comment]
> To be clear, you mean like a screenshot with the various bullet and indentation options (maybe the raw text is also in the documentation too) right?

No, not a screenshot, but a sample file/text snippet and possible a description of how you want it to look. As an example, the following example should now work mostly as expected:

```markdown
* list level 1
* list level 1
  * list level 2
  * list level 2
    on multiple lines
* list level 1
```

**Comment by nathanbraun** [comment]
Ok here you go. I described the only issues I'm seeing in text below.

```markdown
Example:
- Lists with dashes look good.
  - Even at multiple...
    - levels...
      - down.
* Starred lists...
  * look
    * good
      * too.

1. How about ordered lists?
2. ...looks like they work at the top level.

Issues:
- Long list items like this line seem like they switch highlighting on the
  second, wrapped half. <- I.e. this part (and lines after) are the second
  color, seems like it should be the same.
1. Not sure if/how the number portion of numbered bullets are implemented;
   currently seems like they have a fixed color (e.g. not same as other
   bullets). 
```

**Comment by lervag** [comment]
Thanks. I've now created an example file. For me, it does not really work as expected, so I'll keep working on this until things seem robust.

**Comment by lervag** [comment]
I'll close this issue when the [example file](https://github.com/lervag/vim-rainbow-lists/blob/main/test/example.md) is properly colored according to the nested highlighting rules.

Note that ordered lists are different than unordered lists: To increase the level, you need three space indents. I'll look into if it is possible to parse this reliably regardless of what the user is doing.

**Comment by nathanbraun** [comment]
> To increase the level, you need three space indents. I'll look into if it is possible to parse this reliably regardless of what the user is doing.

You're definitely more plugged into proper markdown syntax than I am.  I didn't know that about ordered lists.  In my notes I just set everything:

```
autocmd FileType vimwiki setlocal shiftwidth=2 tabstop=2
```

It'd be nice if it worked with that at some point, but I'm down for improving my note taking (e.g. using 3 spaces for ordered lists) too.

**Comment by lervag** [comment]
Ok, we're getting closer now. I would expect most of your asked for features to work, except perhaps the numbered lists. I'll look into a way of handling them properly.

**Comment by lervag** [comment]
Oh, and checkboxes. Could you explain how you think these should look? Also, feel free to present an example of a checkbox list that does not look as expected.

**Comment by nathanbraun** [comment]
> Oh, and checkboxes. Could you explain how you think these should look? Also, feel free to present an example of a checkbox list that does not look as expected.

Seems like it should just have the `[ ]` and `[X]` parts be the same color as the bullet. So like this:

```
- [o] big task
  - [X] sub task 1
  - [ ] sub task 2
```

It seems like the brackets and whatever is inside (vimwiki defaults to space, `X`, `o` or `.`) should just be the same as bullet. It's really pretty minor but could be good as a finishing touch.

**Comment by lervag** [comment]
Ok, I think things should work in most cases now. Let me know what you think and feel free to open new issues if you have more problems.
