### ISSUE TITLE
not working with bullets.vim

### ISSUE THREAD

**Issue by nathanbraun** [lervag/vim-rainbow-lists#10]
Still been using the plugin every day, thanks.

I tried moving from vimwiki to something else though, and as part of that installed both vim-rainbow-lists and [bullets.vim](https://github.com/dkarter/bullets.vim).  I'm seeing some weird behavior.  Namely, even with `RBListEnable` the highlighting doesn't show up, unless I insert a line above  (with `O`), then I see it, but it disappears when I save the buffer.

Any thoughts or do you think this might be a bullets.vim issue?

**Comment by lervag** [comment]
> Still been using the plugin every day, thanks.

Cool - glad to hear it :)

> I tried moving from vimwiki to something else though, and as part of that installed both vim-rainbow-lists and [bullets.vim](https://github.com/dkarter/bullets.vim). I'm seeing some weird behavior. Namely, even with `RBListEnable` the highlighting doesn't show up, unless I insert a line above (with `O`), then I see it, but it disappears when I save the buffer.
> 
> Any thoughts or do you think this might be a bullets.vim issue?

Good question. Is it possible to get a minimal vimrc file and example for this? That would make it much easier for me to look into it.

**Comment by nathanbraun** [comment]
In the process of trying to set up a minimal vimrc I got it basically working (but may have found another issue).  I'll keep playing around with it/open a new issue if this other thing is problem.  Thank you!

**Comment by lervag** [comment]
Sounds good - feel free to reopen/open a new issue :)
