### ISSUE TITLE
automatically add bullet of the same type when appending line below current line

### ISSUE THREAD

**Issue by nathanbraun** [lervag/vim-rainbow-lists#3]
In vimwiki, if you're on a list item in normal mode and press `o`, it opens up a blank line right below it with the same indentation and inserts a bullet (and a space) for you. When I have `RBListEnable` on, it doesn't add the bullet (I've noticed Junegunn's vim-journal doesn't add the bullet either).  Not a huge deal, but it'd be nice if it did.

**Comment by nathanbraun** [comment]
I suppose a bullet if you append above too with `O`

**Comment by lervag** [comment]
I'm not so sure about this, actually. The behaviour you are asking for here is determined by the `formatoptions` and `formatlistpat` options, which are often specified by a specific filetype plugin. I think if we change these options it could lead to unexpected effects.

Instead, I propose that you alter those options in your own personal config. E.g., you can change this for `.wiki` files by adding a file `~/.vim/after/ftplugin/wiki.vim` with content similar to this:

```vim
if exists('b:did_ftplugin_personal') | finish | endif
let b:did_ftplugin_personal = 1

setlocal formatoptions-=o
setlocal formatoptions+=n
let &l:formatlistpat = '\v^\s*%(\d|\l|i+)\.\s'
```

You can learn more about these options with `:help formatoptions` and `:help formatlistpat`. Note that they are somewhat complex, but if you read the docs carefully it should be not too hard to understand.

**Comment by nathanbraun** [comment]
Definitely have no problem with this approach, but I guess intuitively, I would have expected vim-rainbow-lists to not change this behavior, i.e. if it's applied to a vimwiki filetype file keep adding the bullet like vimwiki does, if it's called on some regular markdown file or something that doesn't do that, then don't.

**Comment by lervag** [comment]
> Definitely have no problem with this approach, but I guess intuitively, I would have expected vim-rainbow-lists to not change this behavior, i.e. if it's applied to a vimwiki filetype file keep adding the bullet like vimwiki does, if it's called on some regular markdown file or something that doesn't do that, then don't.

When you say ", but I guess ... I would have expected ... to **not change** this behaviour", it seems you think vim-rainbow-lists **is** changing the behaviour. As far as I understand, it is not and never did. I understood your original post here as a request to make vim-rainbow-lists add this change of behaviour, which was what I argued against.

But perhaps I'm misinterpreting. I feel you are also saying you agree with my sentiment that vim-rainbow-lists should not alter the behaviour of the current filetype. If so, we'll just leave it at that :)

**Comment by nathanbraun** [comment]
Yes, it is changing the behavior. Say I'm on `my second item` below.

```
- my bullet item
- my second item
```

Currently (without vim-rainbow-lists toggled on), if you press `o` in vimwiki, it'll add a new line with the bullet inserted automatically.  Like this:

```
- my bullet item
- my second item
- 
```

But when vim-rainbow-list is enabled (and I'm still in a vimwiki file), it no longer does that (it's just a blank line). So it's changing the behavior.  I agree it wouldn't add a bullet if we were on a filetype (normal text file or whatever) that didn't do that.

**Comment by lervag** [comment]
Huh, that's very strange. The only thing that is changed is the syntax groups. So, if the behaviour is changed, than that must be because Vimwiki does something strange like remapping `o`?

**Comment by lervag** [comment]
Lo and behold:

* https://github.com/vimwiki/vimwiki/blob/master/ftplugin/vimwiki.vim#L480
* https://github.com/vimwiki/vimwiki/blob/master/autoload/vimwiki/lst.vim#L1466

So, this is precisely what is happening. Although, I do not fully understand what Vimwiki is doing here, but I believe the issue is that the new syntax groups somehow interfere with this function `vimwiki#lst#kbd_o`. And that makes things very hard to fix in general.

**Comment by nathanbraun** [comment]
Interesting, nice debugging instincts! I find myself missing this feature when vim-rainbow-lists is on, so let me know if you have any ideas. If it requires hacking something together/modifying a vimrc I'm fine with that too.

**Comment by lervag** [comment]
One idea: You can create your own custom map for Vimwiki files. I would assume Vimwiki does not override maps that you have already defined. So, create something like `~/.vim/ftplugin/vimwiki.vim` with the following content:

```vim
if exists('b:did_ftplugin_personal') | finish | endif
let b:did_ftplugin_personal = 1

nnoremap <silent><buffer> o :<c-u>call CustomListo()<cr>

function CustomListo() abort
  let l:enabled = rblist#enabled()
  if l:enabled
    call rblist#disable()
  endif
  normal <plug>VimwikiListo
  if l:enabled
    call rblist#enable()
  endif
endfunction
```

I did not test this, but I think the idea should work. This remaps `o` in Vimwiki files with a wrapper that disables the rainbow-lists if it is enabled so that `o` works as it should.

**Comment by lervag** [comment]
Let me know if this works for you. If it does, I assume you can make the same variant for `O` if that is needed.

**Comment by nathanbraun** [comment]
It didn't unfortunately, I played around with it a bit. For one, I'm pretty sure vimwiki *is* overriding my mappings, but even when I tested switching it to something else (e.g. like a leader key), it sort of worked, but not always.

**Comment by lervag** [comment]
> It didn't unfortunately, I played around with it a bit. For one, I'm pretty sure vimwiki _is_ overriding my mappings, but even when I tested switching it to something else (e.g. like a leader key), it sort of worked, but not always.

Strange. Ok, to ensure Vimwiki does not override, you can place the code in `~/.vim/after/ftplugin/vimwiki.vim` - this means you override the Vimwiki mappings.

I would expect the mapping to work, so it would be interesting to hear _how_ it fails when it doesn't.

**Comment by nathanbraun** [comment]
I played around with it a bit more, the following in `~/.vim/after/ftplugin/vimwiki.vim` works:

```vim
if exists('b:did_ftplugin_personal') | finish | endif
let b:did_ftplugin_personal = 1

nnoremap <silent><buffer> o :<c-u>call CustomListo()<cr>
nnoremap <silent><buffer> O :<c-u>call CustomListo()<cr>

function CustomListo()
  let l:enabled = rblist#enabled()
  if l:enabled
    call rblist#disable()
  endif
  call vimwiki#u#count_exe('call vimwiki#lst#kbd_o()')

  if l:enabled
    call rblist#enable()
  endif
endfunction

function CustomListO()
  let l:enabled = rblist#enabled()
  if l:enabled
    call rblist#disable()
  endif
  call vimwiki#u#count_exe('call vimwiki#lst#kbd_O()')

  if l:enabled
    call rblist#enable()
  endif
endfunction
```

Not sure why, but it was doing some weird highlighting thing just calling `normal <plug>VimwikiListo`.  All good now though, thank you!

**Comment by lervag** [comment]
Great, I'm happy you figured it out. A minor improvement:

```vim
if exists('b:did_ftplugin_personal') | finish | endif
let b:did_ftplugin_personal = 1

nnoremap <silent><buffer> o :<c-u>call CustomListO('kbd_o')<cr>
nnoremap <silent><buffer> O :<c-u>call CustomListO('kbd_O')<cr>

function CustomListO(funcname)
  let l:enabled = rblist#enabled()
  if l:enabled
    call rblist#disable()
  endif
  call vimwiki#u#count_exe('call vimwiki#lst#' . a:funcname . '()')
  if l:enabled
    call rblist#enable()
  endif
endfunction
```
