### ISSUE TITLE
add > bullet type

### ISSUE THREAD

**Issue by nathanbraun** [lervag/vim-rainbow-lists#5]
After looking at this a bit in my own notes, I do sometimes use > for quotes. Could we add it to the list of acceptable bullet types?

**Comment by lervag** [comment]
Yes, sure. Although, I would guess quotes are more complex. I.e., we want to support multiple levels, so something like this should be supported:

```
> quote level 1
>
> > quote level 2
> > quote level 2
> > quote level 2
>
> back to level 1
```

Right? Feel free to provide more examples; I'll add them to the example file and then make it work afterwards.

**Comment by nathanbraun** [comment]
I could see something like that being useful. For me, personally in my notes, they're usually one level. Something like this:

```
> "The best founders work on *things that seem small but they move really
  quickly*. Every time you talk to the best founders they’ve gotten new things
  done. In fact, this is the one thing that we learned best predicts a success
  of founders in YC. If every time we talk to a team they’ve gotten new things
  done, that’s the best predictor we have that a company will be successful."
  - Sam Altman
```

Ideally, the quote part would be the top level color, and the attribution the second level.  Right now (this particular quote) the first two lines are uncolored (I think the italics might be doing something), and the rest wrapped part of the quote is highlighted at the second level. This gets at the wrapping this I mentioned in the example in #1 .

Looking at this more, I've also seen this format too (still usually with just the one level), but seems like the current rules would be able to handle it.

```
> "The best founders work on *things that seem small but they move really
> quickly*. Every time you talk to the best founders they’ve gotten new things
> done. In fact, this is the one thing that we learned best predicts a success
> of founders in YC. If every time we talk to a team they’ve gotten new things
> done, that’s the best predictor we have that a company will be successful."
  - Sam Altman
```

So I guess ideally for that the quote would be highlighted at the top level.

**Comment by lervag** [comment]
Thanks. I've added this to the example file and will work on it along with the remaining stuff in #1. I'm closing this issue as I think it is covered by #1.
