### ISSUE TITLE
toggle doesn't work on lists nested more than 4 levels deep

### ISSUE THREAD

**Issue by nathanbraun** [lervag/vim-rainbow-lists#7]
Hi Karl, one very minor issue I noticed is that the toggle (and maybe the other plugins too) doesn't seem to affect lists more than four levels deep.  For example:

```
- level 1
  - level 2
    - level 3
      - level 4
        - toggle doesn't turn off 
          - for these levels
```

Perhaps it's related to `rblist_levels` and how it was originally 4, then became flexible?  Either way, just a heads up. Cheers!

**Comment by lervag** [comment]
Sorry, but I don't follow. What do you mean "doesn't turn off"? Did you mean that there is no separate color for level 5 and beyond? That is probably true, right now there is no automatic definition of colors for more levels, but you can define the colors yourselv. Still, perhaps it is good to at least support  some more levels and also document this specifically?

**Comment by nathanbraun** [comment]
Sorry for the delay in responding — 

I set colors for 5 and beyond myself (and changed `rblist_levels` to 8).  I also have the plugin automatically turn on when I enter my wiki files and have a key mapped to toggle it.

So when I go to a page with more than four levels, everything looks good and is colored according to my configuration.  But when I toggle it with `:RBListToggle`, the coloring turns off only for the first four levels. Levels 5+ remain colored.

This is really minor (both because lists with 5+ levels are rare and it's not a big deal), but wanted to pass along.

**Comment by lervag** [comment]
> I set colors for 5 and beyond myself (and changed `rblist_levels` to 8). I also have the plugin automatically turn on when I enter my wiki files and have a key mapped to toggle it.

It would be very useful to get your full config for this. Mind to share?

**Comment by lervag** [comment]
Ah, I think I found the bug. Please test :)

**Comment by nathanbraun** [comment]
Yep that took care of it, thanks so much Karl!

**Comment by lervag** [comment]
No problem, happy to hear it works :)
